### ISSUE TITLE
Parsing issue using scoped variables imported using `@use`

### ISSUE THREAD

**Issue by assawalhy** [serenadeai/tree-sitter-scss#5]
I encountered a problem with highlighting in Neovim after enabling `highlight` module for **nvim-treesitter**. I also created [this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1790) at nvim-treesitter repo. We concluded that this problem is from the parser, not the highlighting module...

![image](https://user-images.githubusercontent.com/42011920/132905553-21b27212-beab-45bc-a72a-703e8843ee69.png)

**Comment by harrisoncramer** [comment]
I've encountered this same problem with the @apply keyword coming from Tailwind. I'm thinking that the parser is failing to understand the @ keyword (directives).
![Screenshot from 2022-01-12 17-16-15](https://user-images.githubusercontent.com/32515581/149231711-6ee453a5-c0e5-4fd6-a159-2eb5aea1b231.png)

**Comment by tmacwill** [comment]
just added support for the `@apply` keyword. I wasn't able to reproduce the original issue with scoped variables, though—we already have a test for this that currently passes:

```
==============================
Use statements
==============================

@use 'custom.css';

.inverse {
  background-color: base.$primary-color;
  color: white;
}

---

(stylesheet
  (use_statement (string_value))
  (rule_set
    (selectors (class_selector (class_name)))
    (block
      (declaration (property_name) (variable_value))
      (declaration (property_name) (plain_value)))))
```

so, I suspect there might be some other piece of syntax that tree-sitter-scss might not be handling properly. if you're able to post a minimal example that reproduces the issue here, I'd be happy to take a look.
